=== FatLi1989/jtsec-com/jtsec-mc-dev-moitor/jtsec-mc-dev-moitor-service-impl/src/main/resources/jtsec-oid.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:attribute name="value" ></xs:attribute>
<xs:element name="devices">
<xs:complexType>
  <xs:sequence>
  	<xs:element name="global" maxOccurs="1" minOccurs="1">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element name="oid" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:attributeGroup ref="base_attr_group"></xs:attributeGroup>
					</xs:complexType>  					
  				</xs:element>
  			</xs:sequence>
  			<xs:attribute name="encoding" type="xs:string" use="optional" default="UTF-8"></xs:attribute>
  			<xs:attribute name="descript" type="xs:string" use="optional"></xs:attribute>
  		</xs:complexType>
  	</xs:element>
	<xs:element name="device" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="oid" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="oid" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attributeGroup ref="base_attr_group"></xs:attributeGroup>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attributeGroup ref="base_attr_group"></xs:attributeGroup>
						<xs:attribute name="handType" type="xs:string" use="required"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="descript" type="xs:string" use="optional"></xs:attribute>
		</xs:complexType>
	</xs:element>
  </xs:sequence>
 </xs:complexType>
</xs:element>

<xs:attributeGroup name="base_attr_group">
	<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
	<xs:attribute name="tableName" type="xs:string" use="optional" default=""></xs:attribute>
	<xs:attribute name="descript" type="xs:string" use="optional"></xs:attribute>
	<xs:attribute name="dataType" type="xs:string" use="optional"></xs:attribute>
</xs:attributeGroup>
</xs:schema>

=== FatLi1989/jtsec-com/jtsec-mc-dev-moitor/jtsec-mc-dev-moitor-service-impl/src/main/resources/jtsec-oid.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<devices
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="jtsec-oid.xsd">
	<global encoding="GBK">
		<oid value="1.3.6.1.2.1.1.3.0" descript="时间OID"/>
		<oid value="1.3.6.1.6.3.1.1.4.1.0" descript="snmp数据类型OID"/>
	</global>
	<device value="1.3.6.1.4.1.39056" type="two-way" descript="doubleway">
		<oid value="1.3.6.1.4.1.39056.2.2" descript="设备信息" tableName="nem_device_info" handType="devinfo">
			<oid value="1.3.6.1.4.1.39056.1.1" descript="网闸ID"></oid>
			<oid value="1.3.6.1.4.1.39056.1.2" descript="网闸设备信息"></oid>
			<oid value="1.3.6.1.4.1.39056.1.3" descript="网闸设备厂商"></oid>
			<oid value="1.3.6.1.4.1.39056.1.4" descript="软件版本"></oid>
			<oid value="1.3.6.1.4.1.39056.1.5" descript="硬件版本"></oid>
			<oid value="1.3.6.1.4.1.39056.1.6" descript="网闸设备域"></oid>
		</oid>
		<oid value="1.3.6.1.4.1.39056.2.4" descript="CPU使用情况" handType="cpumemuse" tableName="lcaa_type_cpu_use">
			<oid value="1.3.6.1.4.1.39056.1.53" descript="内端机CPU使用情况" dataType="1"/>
			<oid value="1.3.6.1.4.1.39056.1.55" descript="外端机CPU使用情况" dataType="2"/>
		</oid>
		<oid value="1.3.6.1.4.1.39056.2.5" descript="内存使用情况" handType="cpumemuse" tableName="lcaa_type_mem_use">
			<oid value="1.3.6.1.4.1.39056.1.54" descript="内端机内存使用情况" dataType="1"/>
			<oid value="1.3.6.1.4.1.39056.1.56" descript="外端机内存使用情况" dataType="2"/>
		</oid>
		<oid value="1.3.6.1.4.1.39056.2.6" descript="以太网口" handType="netflux" tableName="lcaa_type_net_flux">
			<oid value="1.3.6.1.4.1.39056.1.57" descript="内端机网卡流入" dataType="1" />
			<oid value="1.3.6.1.4.1.39056.1.58" descript="内端机网卡流出" dataType="2" />
			<oid value="1.3.6.1.4.1.39056.1.59" descript="外机网卡流出" dataType="3" />
			<oid value="1.3.6.1.4.1.39056.1.60" descript="外端机网卡流出" dataType="4" />
		</oid>
		<oid value="1.3.6.1.4.1.39056.2.8" descript="代理服务流量" tableName="lcaa_type_serv_flux" handType="servflux"/>
		<oid value="1.3.6.1.4.1.39056.2.17" descript="活动连接数" tableName="lcaa_type_active_conn" handType="activeconn"/>

		<oid value="1.3.6.1.4.1.39056.2.20" descript="内端机接口断开" tableName="lcaa_type_warn" dataType="20" handType="warn"/>
		<oid value="1.3.6.1.4.1.39056.2.21" descript="外端机接口断开" tableName="lcaa_type_warn" dataType="21" handType="warn"/>
		<oid value="1.3.6.1.4.1.39056.2.25" descript="内端机内存溢出" tableName="lcaa_type_warn" dataType="25" handType="warn"/>
		<oid value="1.3.6.1.4.1.39056.2.26" descript="外端机内存溢出" tableName="lcaa_type_warn" dataType="26" handType="warn"/>
		<oid value="1.3.6.1.4.1.39056.2.28" descript="内端机CPU溢出" tableName="lcaa_type_warn" dataType="28" handType="warn"/>
		<oid value="1.3.6.1.4.1.39056.2.29" descript="外端机CPU溢出" tableName="lcaa_type_warn" dataType="29" handType="warn"/>

		<oid value="1.3.6.1.4.1.39056.1.62" descript="内端机CPU使用率阀值(1~99)" tableName="" handType=""/>
		<oid value="1.3.6.1.4.1.39056.1.63" descript="内端机内存使用率阀值(1~99)" tableName="" handType=""/>
		<oid value="1.3.6.1.4.1.39056.1.64" descript="外端机CPU使用率阀值(1~99)" tableName="" handType=""/>
		<oid value="1.3.6.1.4.1.39056.1.65" descript="外端机内存使用率阀值(1~99)" tableName="" handType=""/>

	</device>

	<device value="1.3.6.1.4.1.39056.2" type="one-way" descript="singleway" >
		<oid value="1.3.6.1.4.1.39056.2.2.2" handType="aa"/>
	</device>
</devices>
